# app/config/security.yml

security:
    encoders:        
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_AUTEUR:      [ROLE_USER]
        ROLE_MODERATEUR:  [ROLE_USER, ROLE_AUTEUR ]
        ROLE_ADMIN:       [ROLE_USER, ROLE_AUTEUR, ROLE_MODERATEUR, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
           main:
                id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret%

    access_control:   # si no pongo esto cuando quiero hacer un comentario y no soy user no me presenta la conexion y da error
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/commenter/, roles: ROLE_USER }  
        - { path: ^/ajouter_post/, roles: ROLE_ADMIN }
