# C:\wamp\www\Siteperso\src\AppBundle\Resources\config\routing.yml

app_accueil:
    path:      /
    defaults:  { _controller: AppBundle:Default:accueil }

app_contact:
    path:      /contact
    defaults:  { _controller: AppBundle:Default:contact }

app_blog:
    path:      /blog
    defaults:  { _controller: AppBundle:Blog:blog }

app_article:
    path:      /article/{id}
    defaults:  { _controller: AppBundle:Blog:article }
    requeriments:
        id:  \id+

app_ajouter:
    path:      /ajouter/{id}
    defaults:  { _controller: AppBundle:Blog:ajouter }
    requeriments:
        id:  \id+	

app_modifier:
    path:      /modifier{id}
    defaults:  { _controller: AppBundle:Blog:modifier }

app_supprimer:
    path:      /supprimer{id}
    defaults:  { _controller: AppBundle:Blog:supprimer }