<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param string $orderBy   Le champ sur lequel on trie les Posts (auteur ou date)
     * @param string $direction L'ordre dans lequel on trie les Posts (ASC ou DESC)
     * @param array  $auteurs   Les auteurs que l'on veut voir uniquement.
     *
     * @return array
     */
    public function myFindAll($orderBy = null, $direction = null, array $auteurs = null)
    {
        $req = $this->createQueryBuilder('p');

        // Critères de sélection
        if (count($auteurs)) {
            // Critères de sélection
            $req->where('p.auteur IN ( :auteurs )');
            $req->setParameter(':auteurs', $auteurs);
        }

        // Critères de tri
        if ($orderBy) {
            // $orderBy === 'auteur'
            // $orderBy === 'date'
            // $direction === 'DESC'
            // $direction === 'ASC'
            $req->orderBy('p.'.$orderBy, $direction);
        }

        return $req->getQuery()->getResult();
    }


}
